
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "consulate/model.zep.h"
#include "consulate/api/endpoint.zep.h"
#include "consulate/exception.zep.h"
#include "consulate/values.zep.h"
#include "consulate/api/agent/servicecheck.zep.h"
#include "consulate/api/acl.zep.h"
#include "consulate/api/agent.zep.h"
#include "consulate/api/agent/check.zep.h"
#include "consulate/api/agent/checkregistration.zep.h"
#include "consulate/api/agent/exception.zep.h"
#include "consulate/api/agent/gaugevalue.zep.h"
#include "consulate/api/agent/member.zep.h"
#include "consulate/api/agent/metricsinfo.zep.h"
#include "consulate/api/agent/pointvalue.zep.h"
#include "consulate/api/agent/sampledvalue.zep.h"
#include "consulate/api/agent/service.zep.h"
#include "consulate/api/agent/serviceregistration.zep.h"
#include "consulate/api/catalog.zep.h"
#include "consulate/api/catalog/node.zep.h"
#include "consulate/api/coordinate.zep.h"
#include "consulate/api/event.zep.h"
#include "consulate/api/exception.zep.h"
#include "consulate/api/health.zep.h"
#include "consulate/api/health/check.zep.h"
#include "consulate/api/health/exception.zep.h"
#include "consulate/api/health/service.zep.h"
#include "consulate/api/kv.zep.h"
#include "consulate/api/kv/exception.zep.h"
#include "consulate/api/kv/pair.zep.h"
#include "consulate/api/operator.zep.h"
#include "consulate/api/query.zep.h"
#include "consulate/api/session.zep.h"
#include "consulate/api/snapshot.zep.h"
#include "consulate/api/status.zep.h"
#include "consulate/client.zep.h"
#include "consulate/config.zep.h"
#include "consulate/http/auth.zep.h"
#include "consulate/http/client/curl.zep.h"
#include "consulate/http/client/exception.zep.h"
#include "consulate/http/exception.zep.h"
#include "consulate/http/headers.zep.h"
#include "consulate/http/params.zep.h"
#include "consulate/http/request.zep.h"
#include "consulate/http/response.zep.h"
#include "consulate/http/uri.zep.h"
#include "consulate/querymeta.zep.h"
#include "consulate/queryoptions.zep.h"
#include "consulate/writemeta.zep.h"
#include "consulate/writeoptions.zep.h"
#include "consulate/0__closure.zep.h"
#include "consulate/1__closure.zep.h"

#endif